name: Staging CI/CD Pipeline

on:
  push:
    branches: [ staging ]

env:
  AWS_REGION: ca-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  staging_deploy_iac:
    runs-on: ubuntu-20.04
    environment: staging
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    
      - uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init -backend-config=config/backend-config.tf -reconfigure -input=false -upgrade 

      - name: Terraform - Unlocking
        id: unlock
        if: ${{ env.TF_LOCK_ENABLED }}
        run: terraform force-unlock -force ${{ secrets.TF_LOCK_ID }}
        continue-on-error: true
        timeout-minutes: 2

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=environments/staging.tfvars -input=false -out saved_plan

      - name: Terraform Apply
        run: terraform apply -auto-approve saved_plan